name: DSN Analysis (min)

on:
  workflow_dispatch:
    inputs:
      label:
        required: true
      from:
        required: true
      to:
        required: true

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "label=${{ github.event.inputs.label }}"
          echo "from=${{ github.event.inputs.from }}"
          echo "to=${{ github.event.inputs.to }}"
